services:
  front:
    image: ghcr.io/thedmdim/new.psy-sobytie/front:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - back

  back:
    image: ghcr.io/thedmdim/new.psy-sobytie/back:latest
    restart: unless-stopped
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_GROUP_ID=${TG_GROUP_ID}